[db]
engine = "sqlite"
path   = "data/db/poo.db"

[paths]
gcode = "data/trayectorias"     # carpeta para archivos de trayectorias
logs  = "data/logs/server_log.csv"

[security]
password_salt = "cambia_este_salt"   # si por ahora no usás bcrypt


